spring:

  profiles:
    active: @activatedProperties@

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=public
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.AtomikosJtaPlatform
    open-in-view: false

  jta:
    atomikos:
      properties:
        enable-logging: true
        max-timeout: 900000
        service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
    enabled: true


  mvc:
    problemdetails:
      enabled: true

logging:
  level:
    com.atomikos: ${ATOMIKOS_LOG:INFO}
    org.springframework.cache: ${CACHE_LOG:INFO}
    org.springframework.web.cors: ${CORS_LOG:INFO}
    org.hibernate: ${HIBERNATE:INFO}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token:
      expiration: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token:
      expiration: ${REFRESH_TOKEN_EXPIRATION}