spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lifecompanion?currentSchema=public
    username: postgres
    password: admin

  mvc:
    problemdetails:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    secret: V9/SufWK2PdgoC9u6wxr2mLvK7PK5s0JvBkbu24v8yg=
    expiration: 604800000

