spring:

  profiles:
    active: @activatedProperties@

  datasource:
    type: com.atomikos.spring.AtomikosDataSourceBean
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=public
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.AtomikosJtaPlatform
    open-in-view: false

  liquibase:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=public
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: false

  jta:
    enabled: true
    atomikos:
      datasource:
        min-pool-size: 5
        max-pool-size: 20
        unique-resource-name: life-companion

  mvc:
    problemdetails:
      enabled: true

logging:
  level:
    com.atomikos: ${ATOMIKOS_LOG:INFO}
    org.springframework.cache: ${CACHE_LOG:INFO}
    org.springframework.web.cors: ${CORS_LOG:INFO}
    org.hibernate: ${HIBERNATE:INFO}
    org.hibernate.orm.jdbc.bind: ${HIBERNATE_PARAMETER:INFO}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token:
      expiration: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token:
      expiration: ${REFRESH_TOKEN_EXPIRATION}