spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lifecompanion?currentSchema=public
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.AtomikosJtaPlatform
    open-in-view: false

  jta:
    atomikos:
      properties:
        enable-logging: true
        max-timeout: 900000
        service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
    enabled: true


  mvc:
    problemdetails:
      enabled: true

logging:
  level:
    com.atomikos: DEBUG

app:
  jwt:
    secret: V9/SufWK2PdgoC9u6wxr2mLvK7PK5s0JvBkbu24v8yg=
    expiration: 604800000

