# Database

DB_HOST: localhost
DB_PORT: 5432
DB_NAME: lifecompanion
DB_USERNAME: postgres
DB_PASSWORD: admin

# Logging

ATOMIKOS_LOG: TRACE
CACHE_LOG: TRACE
CORS_LOG: TRACE

# App JWT Token

JWT_SECRET: d56d9e98eddf914b95d670cd4991afda46f943fb7d28fa64d6170fb45cf1ad11771ca8f7104b824809bccbfc834a39170a0fe14397f0bde8cbdb9e54cc3344f2
ACCESS_TOKEN_EXPIRATION: 86400000
REFRESH_TOKEN_EXPIRATION: 604800000