package dev.shade.domain.person;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * <p>The {@code Locality} enum represents various localities in the beautiful country of Mauritius.
 * Each enum value corresponds to a specific locality on the island, providing a convenient way
 * to reference these places in Java code.</p><br>
 *
 * <p>Use this enum to work with localities in Mauritius programmatically, whether for data processing,
 * geographic analysis, or any other purpose that requires the identification of these locations.</p><br>
 *
 * <p>Note: The enum values are in uppercase to ensure consistency and avoid potential naming issues.</p><br>
 *
 * @author Shade
 * @version 1.0
 */
@RequiredArgsConstructor
@Getter
public enum Locality {

    AGALEGA("Agalega"),
    ALBION("Albion"),
    AMITIE_GOKHOOLA("Amitie Gokhoola"),
    ARSENAL("Arsenal"),
    BAIE_DU_CAP("Baie Du Cap"),
    BAMBOUS("Bambous"),
    BAMBOUS_VIRIEUX("Bambous Virieux"),
    BANANES("Bananes"),
    BEAU_BASSIN("Beau Bassin"),
    BEAU_VALLON("Beau Vallon"),
    BEL_AIR("Bel Air"),
    BEL_OMBRE("Bel Ombre"),
    BENARES("Benares"),
    BLACK_RIVER("Black River"),
    BOIS_CHERI("Bois Cheri"),
    BOIS_DES_AMOURETTES("Bois Des Amourettes"),
    BON_ACCUEIL("Bon Accueil"),
    BRAMSTHAN("Bramsthan"),
    BRISEE_VERDIERE("Brisee Verdiere"),
    BRITANNIA("Britannia"),
    CALEBASSES("Calebasses"),
    CAMP_CAROL("Camp Carol"),
    CAMP_DE_MASQUE("Camp De Masque"),
    CAMP_DE_MASQUE_PAVE("Camp De Masque Pave"),
    CAMP_DIABLE("Camp Diable"),
    CAMP_ITHIER("Camp Ithier"),
    CAP_MALHEUREUX("Cap Malheureux"),
    CASCAVELLE("Cascavelle"),
    CASE_NOYALE("Case Noyale"),
    CENTRAL_FLACQ("Central Flacq"),
    CHAMAREL("Chamarel"),
    CHAMOUNY("Chamouny"),
    CHEMIN_GRENIER("Chemin Grenier"),
    CLEMENCIA("Clemencia"),
    CLUNY("Cluny"),
    CONGOMAH("Congomah"),
    COTTAGE("Cottage"),
    CREVE_COEUR("Creve Coeur"),
    CUREPIPE("Curepipe"),
    D_EPINAY("D'Epinay"),
    DAGOTIERE("Dagotiere"),
    DUBREUIL("Dubreuil"),
    EAU_COULEE("Eau Coulee"),
    EBENE("Ebene"),
    ECROIGNARD("Ecroignard"),
    FOREST_SIDE("FOREST - SIDE"),
    FLIC_EN_FLAC("Flic en Flac"),
    FOND_DU_SAC("Fond du Sac"),
    GRSE("G.R.S.E"),
    GOODLANDS("Goodlands"),
    GRAND_BAY("Grand Bay"),
    GRAND_BEL_AIR("Grand Bel Air"),
    GRAND_BOIS("Grand Bois"),
    GRAND_GAUBE("Grand Gaube"),
    GRAND_SABLE("Grand Sable"),
    GRANDE_RETRAITE("Grande Retraite"),
    GROS_CAILLOUX("Gros Cailloux"),
    L_AVENIR("L'Avenir"),
    L_ESCALIER("L'Escalier"),
    L_ESPERANCE("L'Esperance"),
    L_ESPERANCE_TREBUCHET("L'Esperance Trebuchet"),
    LA_FLORA("La Flora"),
    LA_GAULETTE("La Gaulette"),
    LA_LAURA_MALENGA("La Laura / Malenga"),
    LALMATIE("Lalmatie"),
    LAVENTURE("Laventure"),
    LE_HOCHET("Le Hochet"),
    LE_MORNE("Le Morne"),
    LONG_MOUNTAIN("Long Mountain"),
    MAHEBOURG("Mahebourg"),
    MAPOU("Mapou"),
    MARE_D_ALBERT("Mare D'Albert"),
    MARE_LA_CHAUX("Mare La Chaux"),
    MARE_TABAC("Mare Tabac"),
    MEDINE_CAMP_DE_MASQUE("Medine Camp de Masque"),
    MELROSE("Melrose"),
    MIDLANDS("Midlands"),
    MOKA("Moka"),
    MONTAGNE_BLANCHE("Montagne Blanche"),
    MORC_ST_ANDRE("Morc St Andre"),
    NEW_GROVE("New Grove"),
    NOTRE_DAME("Notre Dame"),
    NOUVELLE_DECOUVERTE("Nouvelle Decouverte"),
    NOUVELLE_FRANCE("Nouvelle France"),
    OLD_GRAND_PORT("Old Grand Port"),
    OLIVIA("Olivia"),
    PORT_LOUIS("PORT LOUIS"),
    PAMPLEMOUSSES("Pamplemousses"),
    PETIT_BEL_AIR("Petit Bel Air"),
    PETIT_RAFFRAY("Petit Raffray"),
    PETITE_RIVIERE("Petite Riviere"),
    PHOENIX("Phoenix"),
    PITON("Piton"),
    PLAINE_MAGNIEN("Plaine Magnien"),
    PLAINE_DES_PAPAYES("Plaine des Papayes"),
    POINTE_AUX_PIMENTS("Pointe aux Piments"),
    POINTE_AUX_SABLES("Pointe aux Sables"),
    POSTE_DE_FLACQ("Poste de Flacq"),
    POUDRE_D_OR_HAMLET("Poudre D'Or Hamlet"),
    POUDRE_D_OR_VILLAGE("Poudre D'Or Village"),
    PROVIDENCE("Providence"),
    QUATRE_BORNES("QUATRE BORNES"),
    QUARTIER_MILITAIRE("Quartier Militaire"),
    QUATRE_COCOS("Quatre Cocos"),
    QUATRE_SOEURS("Quatre Soeurs"),
    QUEEN_VICTORIA("Queen Victoria"),
    REDUIT("Reduit"),
    RICHELIEU("Richelieu"),
    RIPAILLES("Ripailles"),
    RIVIERE_DES_ANGUILLES("Riviere des Anguilles"),
    RIVIERE_DES_CREOLES("Riviere des Creoles"),
    RIVIERE_DU_POSTE("Riviere du Poste"),
    RIVIERE_DU_REMPART("Riviere du Rempart"),
    ROCHE_TERRE("Roche Terre"),
    ROCHES_NOIRES("Roches Noires"),
    RODRIGUES_GRAND_MONTAGNE("Rodrigues - Grand Montagne"),
    RODRIGUES_LA_FERME("Rodrigues - La Ferme"),
    RODRIGUES_MONT_LUBIN("Rodrigues - Mont Lubin"),
    RODRIGUES_PORT_MATHURIN("Rodrigues - Port Mathurin"),
    RODRIGUES_RIVIERE_COCO("Rodrigues - Riviere Coco"),
    ROSE_BELLE("Rose Belle"),
    ROSE_HILL("Rose- Hill"),
    SAINT_JULIEN_VILLAGE("Saint Julien Village"),
    SAINT_JULIEN_DHOTMAN("Saint Julien d'Hotman"),
    SAINT_PIERRE("Saint Pierre"),
    SEBASTOPOL("Sebastopol"),
    SOUILLAC("Souillac"),
    ST_HUBERT("St Hubert"),
    SURINAM("Surinam"),
    TAMARIN("Tamarin"),
    TERRE_ROUGE("Terre Rouge"),
    THE_VALE("The Vale"),
    TOMBEAU_BAY("Tombeau Bay"),
    TRIOLET("Triolet"),
    TROIS_BOUTIQUES("Trois Boutiques"),
    TROU_D_EAU_DOUCE("Trou D'Eau Douce"),
    TROU_AUX_BICHES("Trou aux Biches"),
    TYACK("Tyack"),
    UNION_DUCRAY_ST_AUBIN("Union Ducray / St Aubin"),
    UNION_PARK("Union Park"),
    VACOAS_FLOREAL("Vacoas / Floreal"),
    VERDUN("Verdun"),
    VILLE_BAGUE("Ville Bague"),
    SEIZIEME_MILLE("16eme Mille");

    private final String name;

}

