apiVersion: v1
kind: BuildConfig
metadata:
  name: life-companion-app-build
spec:
  source:
    git:
      uri: https://github.com/shade-sdev/life-companion.git
      ref: master
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: quay.io/redcapcloud/openjdk:17
  output:
    to:
      kind: ImageStreamTag
      name: life-companion-app:latest