apiVersion: apps/v1
kind: Deployment
metadata:
  name: life-companion-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: life-companion-app
  template:
    metadata:
      labels:
        app: life-companion-app
    spec:
      containers:
        - name: life-companion-app
          image: life-companion-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: openshift
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_secret
            - name: ACCESS_TOKEN_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: access_token_expiration
            - name: REFRESH_TOKEN_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: refresh_token_expiration
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"