apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_username: QkFTRTY0X0VOQ09ERURfVVNFUk5BTUU=
  db_password: QkFTRTY0X0VOQ09ERURfVVNFUk5BTUU=
  jwt_secret: QkFTRTY0X0VOQ09ERURfVVNFUk5BTUU=