openapi: 3.0.0
info:
  title: Locality Enum
  version: 1.0.0
paths: {}
components:
  schemas:
    LocalityEnum:
      type: string
      enum:
        - AGALEGA
        - ALBION
        - AMITIE_GOKHOOLA
        - ARSENAL
        - BAIE_DU_CAP
        - BAMBOUS
        - BAMBOUS_VIRIEUX
        - BANANES
        - BEAU_BASSIN
        - BEAU_VALLON
        - BEL_AIR
        - BEL_OMBRE
        - BENARES
        - BLACK_RIVER
        - BOIS_CHERI
        - BOIS_DES_AMOURETTES
        - BON_ACCUEIL
        - BRAMSTHAN
        - BRISEE_VERDIERE
        - BRITANNIA
        - CALEBASSES
        - CAMP_CAROL
        - CAMP_DE_MASQUE
        - CAMP_DE_MASQUE_PAVE
        - CAMP_DIABLE
        - CAMP_ITHIER
        - CAP_MALHEUREUX
        - CASCAVELLE
        - CASE_NOYALE
        - CENTRAL_FLACQ
        - CHAMAREL
        - CHAMOUNY
        - CHEMIN_GRENIER
        - CLEMENCIA
        - CLUNY
        - CONGOMAH
        - COTTAGE
        - CREVE_COEUR
        - CUREPIPE
        - D_EPINAY
        - DAGOTIERE
        - DUBREUIL
        - EAU_COULEE
        - EBENE
        - ECROIGNARD
        - FOREST_SIDE
        - FLIC_EN_FLAC
        - FOND_DU_SAC
        - GRSE
        - GOODLANDS
        - GRAND_BAY
        - GRAND_BEL_AIR
        - GRAND_BOIS
        - GRAND_GAUBE
        - GRAND_SABLE
        - GRANDE_RETRAITE
        - GROS_CAILLOUX
        - L_AVENIR
        - L_ESCALIER
        - L_ESPERANCE
        - L_ESPERANCE_TREBUCHET
        - LA_FLORA
        - LA_GAULETTE
        - LA_LAURA_MALENGA
        - LALMATIE
        - LAVENTURE
        - LE_HOCHET
        - LE_MORNE
        - LONG_MOUNTAIN
        - MAHEBOURG
        - MAPOU
        - MARE_D_ALBERT
        - MARE_LA_CHAUX
        - MARE_TABAC
        - MEDINE_CAMP_DE_MASQUE
        - MELROSE
        - MIDLANDS
        - MOKA
        - MONTAGNE_BLANCHE
        - MORC_ST_ANDRE
        - NEW_GROVE
        - NOTRE_DAME
        - NOUVELLE_DECOUVERTE
        - NOUVELLE_FRANCE
        - OLD_GRAND_PORT
        - OLIVIA
        - PORT_LOUIS
        - PAMPLEMOUSSES
        - PETIT_BEL_AIR
        - PETIT_RAFFRAY
        - PETITE_RIVIERE
        - PHOENIX
        - PITON
        - PLAINE_MAGNIEN
        - PLAINE_DES_PAPAYES
        - POINTE_AUX_PIMENTS
        - POINTE_AUX_SABLES
        - POSTE_DE_FLACQ
        - POUDRE_D_OR_HAMLET
        - POUDRE_D_OR_VILLAGE
        - PROVIDENCE
        - QUATRE_BORNES
        - QUARTIER_MILITAIRE
        - QUATRE_COCOS
        - QUATRE_SOEURS
        - QUEEN_VICTORIA
        - REDUIT
        - RICHELIEU
        - RIPAILLES
        - RIVIERE_DES_ANGUILLES
        - RIVIERE_DES_CREOLES
        - RIVIERE_DU_POSTE
        - RIVIERE_DU_REMPART
        - ROCHE_TERRE
        - ROCHES_NOIRES
        - RODRIGUES_GRAND_MONTAGNE
        - RODRIGUES_LA_FERME
        - RODRIGUES_MONT_LUBIN
        - RODRIGUES_PORT_MATHURIN
        - RODRIGUES_RIVIERE_COCO
        - ROSE_BELLE
        - ROSE_HILL
        - SAINT_JULIEN_VILLAGE
        - SAINT_JULIEN_DHOTMAN
        - SAINT_PIERRE
        - SEBASTOPOL
        - SOUILLAC
        - ST_HUBERT
        - SURINAM
        - TAMARIN
        - TERRE_ROUGE
        - THE_VALE
        - TOMBEAU_BAY
        - TRIOLET
        - TROIS_BOUTIQUES
        - TROU_D_EAU_DOUCE
        - TROU_AUX_BICHES
        - TYACK
        - UNION_DUCRAY_ST_AUBIN
        - UNION_PARK
        - VACOAS_FLOREAL
        - VERDUN
        - VILLE_BAGUE
        - SEIZIEME_MILLE
